package ru.divanov.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-09-13T16:32:16.812+03:00
 * Generated source version: 3.5.3
 *
 */
@WebService(targetNamespace = "http://ru.divanov/", name = "MathWebService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MathWebService {

    @WebMethod(action = "http://ru.divanov/")
    @WebResult(name = "getSolutionQuadraticEducationResponse", targetNamespace = "http://ru.divanov", partName = "getSolutionQuadraticEducationResponse")
    public GetSolutionQuadraticEquationResponse getSolutionQuadraticEducation(

        @WebParam(partName = "getSolutionQuadraticEducation", name = "getSolutionQuadraticEducation", targetNamespace = "http://ru.divanov")
        GetSolutionQuadraticEducation getSolutionQuadraticEducation
    ) throws QuadraticEducationException_Exception;
}
