package ru.divanov.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-09-13T16:32:16.822+03:00
 * Generated source version: 3.5.3
 *
 */
@WebServiceClient(name = "MathWebService",
                  wsdlLocation = "http://localhost:8080/services/MathWebServiceEndpoint?wsdl",
                  targetNamespace = "http://ru.divanov")
public class MathWebService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ru.divanov", "MathWebService");
    public final static QName MathWebServicePort = new QName("http://ru.divanov", "MathWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/services/MathWebServiceEndpoint?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MathWebService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/services/MathWebServiceEndpoint?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MathWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MathWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MathWebService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MathWebService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MathWebService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MathWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MathWebService
     */
    @WebEndpoint(name = "MathWebServicePort")
    public MathWebService getMathWebServicePort() {
        return super.getPort(MathWebServicePort, MathWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MathWebService
     */
    @WebEndpoint(name = "MathWebServicePort")
    public MathWebService getMathWebServicePort(WebServiceFeature... features) {
        return super.getPort(MathWebServicePort, MathWebService.class, features);
    }

}
