
package ru.divanov.ws.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-09-13T16:32:16.710+03:00
 * Generated source version: 3.5.3
 */
public final class MathWebService_MathWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://ru.divanov", "MathWebService");

    private MathWebService_MathWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MathWebService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        MathWebService_Service ss = new MathWebService_Service(wsdlURL, SERVICE_NAME);
        MathWebService port = ss.getMathWebServicePort();

        {
            System.out.println("Invoking getSolutionQuadraticEducation...");
            ru.divanov.ws.client.GetSolutionQuadraticEducation _getSolutionQuadraticEducation_getSolutionQuadraticEducation = new GetSolutionQuadraticEducation();
            try {
                _getSolutionQuadraticEducation_getSolutionQuadraticEducation.setA(1);
                _getSolutionQuadraticEducation_getSolutionQuadraticEducation.setB(6);
                _getSolutionQuadraticEducation_getSolutionQuadraticEducation.setC(7);
                ru.divanov.ws.client.GetSolutionQuadraticEquationResponse _getSolutionQuadraticEducation__return = port.getSolutionQuadraticEducation(_getSolutionQuadraticEducation_getSolutionQuadraticEducation);
                System.out.println("getSolutionQuadraticEducation.result=" + _getSolutionQuadraticEducation__return);

            } catch (QuadraticEducationException_Exception e) {
                System.out.println("Expected exception: QuadraticEducationException has occurred.");
                System.out.println(e.toString());
            }

        }

        System.exit(0);
    }

}
