
package ru.divanov.ws.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-09-13T16:32:16.799+03:00
 * Generated source version: 3.5.3
 */

@WebFault(name = "QuadraticEducationException", targetNamespace = "http://ru.divanov/")
public class QuadraticEducationException_Exception extends Exception {

    private ru.divanov.ws.client.QuadraticEducationException faultInfo;

    public QuadraticEducationException_Exception() {
        super();
    }

    public QuadraticEducationException_Exception(String message) {
        super(message);
    }

    public QuadraticEducationException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public QuadraticEducationException_Exception(String message, ru.divanov.ws.client.QuadraticEducationException quadraticEducationException) {
        super(message);
        this.faultInfo = quadraticEducationException;
    }

    public QuadraticEducationException_Exception(String message, ru.divanov.ws.client.QuadraticEducationException quadraticEducationException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = quadraticEducationException;
    }

    public ru.divanov.ws.client.QuadraticEducationException getFaultInfo() {
        return this.faultInfo;
    }
}
